PACKAGE_NAME="s2igevfilter"
PACKAGE_VERSION="2.7.5"

MAKE[0]="make -C src/ KERNELRELEASE=${kernelver}"
CLEAN="make -C src/ clean"
BUILT_MODULE_NAME[0]="s2igevfilter"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/"

AUTOINSTALL="yes"
